### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by egor-rusnak** [egor-rusnak/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by ydRusnak** [comment]
<h1>Résumé</h1>
<p>
&mdash; I do not compete with others, the only competition that challenges me is myself. As a fighter,
friend and an employee I am known as contemplative, tortured and driven.</p>

**Comment by egor-rusnak** [comment]
**Nice. good job** @ydRusnak!(me) 👍😄✔️
