### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by egor-rusnak** [egor-rusnak/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by ydRusnak** [comment]
<h1 class="name">Ryu Hoshi (リュウ Ryū)</h1>
<div class="job">Roleplay</div>
<ul class="contacts">
  <li>
    <a href="https://www.facebook.com/profile.php?id=100004808958030" rel="author" class="facebook">
      <span>Ryu Hoshi (リュウ)</span>
    </a>
  </li>
  <li>
    <a href="mailto:ryuwins@gmail.com" rel="author" class="mail">
      <span>ryuwins@gmail.com</span>
    </a>
  </li>
  <li>
    <a href="https://twitter.com/denjinryu" rel="author" class="twitter">
      <span>@DenjinRyu</span>
    </a>
  </li>
  <li>
    <a href="https://www.instagram.com/sworn_ryu/" rel="author" class="instagram">
      <span>sworn_ryu</span>
    </a>
  </li>
</ul>

**Comment by egor-rusnak** [comment]
### Nice 👍
