### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by egor-rusnak** [egor-rusnak/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by ydRusnak** [comment]
<section>
  <h3>ACHIVEMENTS</h3>
  <ul>
    <li>#1 in "Top 25 Street Fighter Characters" by IGN, who also called me "fancy", "icon" and "a testament to the virtue of simplicity" ❤️</li>
    <li>
      #2 in "Top 20 Street Fighter Characters of All Time" by GameDaily, same council found me worth of #6 place in "Top 25 Capcom Characters of All Time", which I proudly share with my partner Ken
    </li>
    <li>I was named "5th Most Powerful Street Fighter Character" by Screen Rant-san</li>
    <li>#71 in "Top 100 Heroes of All Time" by UGO Networks, also recognized #2 in their list of "Top 50 Street Fighter Characters"</li>
    <li>In a survey of 4000 online matches for Super Street Fighter IV, I got to be the most popular character, with 16.6% of players choosing my side</li>
  </ul>
</section>
<section>
  <h3>LIFE & EDUCATION</h3>
  <p class="tags small">
    To live is to fight and to fight is to live. I started learning fighting at my master Gouken's castle, I was beaten at head way too often to remember when exactly.
  </p>
</section>
<section>
  <h3>LANGUAGES</h3>
  <p class="tags small">
   🇺🇸 ENGLISH
  </p>
  <p class="tags small">
    🇨🇳 MANDARIN
  </p>
  <p class="tags small">
    🇯🇵 JAPANESE
  </p>
</section>
<section>
  <h3>SKILLS</h3>
  <p class="tags small">
    KARATE 
    <span class="nowrap">ENERGY ATTACK SHORYUKEN</span> 
    <span class="nowrap">WALKING BAREFOOT</span>
    <span class="nowrap">PLAYING VIDEOGAMES</span>
    <span class="nowrap">DOING BURGERS</span>
      HADOKEN
    <span class="nowrap">MASHING POTATOES</span> 
    <span class="nowrap">COPYWRITING ACTING VOICEOVERS</span>
  </p>
</section>
<section>
  <h3>CHARACTER</h3>
  <p class="tags small">
    NOBLE DIRECT BOLD CONFIDENT DARING SCHIZOPHRENIC DRAMATIC PERSUASIVE IMMEDIATE WISE
  </p>
</section>
<section>
  <h3>LIFE LESSON</h3>
  <span class="tags small">
    YOU MUST DEFEAT SHENG LONG TO STAND A CHANCE.
  </span>
</section>
<section>
  <h3>LIKES 😃</h3>
  <p class="tags small">
    GI VEGETABLES BLOOD 
    <span class="nowrap">SMALL MARSHMELLOWS</span>
    <span class="nowrap" title="yes, it's more red than anything else, a true red" style="color:red;"><strong>RED COLOR</strong></span>
    <span class="nowrap">KILLED ENEMY</span>
  </p>
</section>
<section>
  <h3>DISLIKES 😞</h3>
  <p class="tags small">
    BISONS GHOSTS SMARTPHONES
    <span class="nowrap">SMELL OF SEAFOOD</span>
    <span class="nowrap">BARBER SHOPS</span> 
    SLEEVES
  </p>
</section>
<section>
  <h3>WANTS🥺</h3>
  <p class="tags small bulleted">
    <span class="tag">BE FIT</span>
    <span class="tag">WRITE MORE BOOKS</span>
    <span class="tag">FIND A GIRLFRIEND TO GO TO CINEMA WITH KILL ALL OF AKUMA FAMILY</span>
  </p>
</section>
<section>
  <h3>ARTICLES</h3>
  <ul class="timeline">
    <li>
      <p class="date">2011</p>
      <p>
        The true and humble story of me under pseudonim Tyler Wilde in an article "The evolution of Ken and Ryu"
      </p>
    </li>
    <li>
      <p class="date">
        2003-2018
      </p>
      <p>
          For 15 years I have published comic books with Udon Entertainment depicting my adventures, bitter lessons and great victories.
      </p>
   </li>
  </ul>
</section>

**Comment by egor-rusnak** [comment]
Good timeline, good work
